<?php
/**
 * @file
 * Code for the Slider feature.
 */

include_once 'slider.features.inc';

function slider_theme($existing, $type, $theme, $path) {
  return array (
    'views_view__slider_view__block' => array (
      'variables' => array('view' => NULL,),
      'template' => 'views-view--slider-view--block' ,
      'base hook' => 'views_view',
      'path' => drupal_get_path('module', 'slider'),
    ),
  );
}
