<?php

/**
 * Implments hook_theme
 */
function tcss_cart_theme() {
 return array(
    'abc_thumb_upload' => array(
        'render element' => 'element',
  ));
}

/**
 * Implments hook_menu
 */
function tcss_cart_menu() {
  $items = array();

  $items['artwork'] = array(
    'title' => 'Your Artwork',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('upload_customer_artwork'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Form for uploading customer design
 */
function upload_customer_artwork($form, &$form_state) {
  if (!isset($_SESSION['customer_artwork_pid'])) {
   drupal_set_message(t('Your session has expired, so please again add the product to cart.'), 'error');
   return '';
  }

  $form['customer_artwork'] = array(
    '#title' => t('Upload Artwork'),
    '#type' => 'managed_file',
    '#description' => t('Upload you design for product'),
    '#upload_location' => 'public://',
    '#theme' => 'abc_thumb_upload',
  );

  $form['customer_artwork_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Submit handler for upload_customer_artwork form
 */
function upload_customer_artwork_submit($form, &$form_state) {
  // Set product and image information to session, used in storing customer's artwork
  if (isset($_SESSION['customer_artwork_pid'])) {
    $_SESSION['customer_artwork_fpid'][$_SESSION['customer_artwork_pid']] = $form_state['values']['customer_artwork'];
    $form_state['redirect'] = 'cart';
    unset($_SESSION['customer_artwork_pid']);
  }
}

/**
 * Implments hook_form_alter
 */
function tcss_cart_form_alter(&$form, &$form_state, $form_id) {
  // Set product information to session, used in storing customer's artwork
  if (strpos($form_id,'uc_product_add_to_cart_form_') !== false) {
    $_SESSION['customer_artwork_pid'] = $form_state['build_info']['args'][0]->nid;
  }

  switch ($form_id) {
    case 'uc_cart_view_form':
    // Disable quanitity field in cart view form
      $i = 0;
      while (TRUE) {
        if (isset($form['items'][$i]['qty'])) {
          $form['items'][$i]['qty']['#disabled'] = TRUE;
          $i++;
        }
        else {
          break;
        }
      }
      break;

    default:
      # code...
      break;
  }
}

function theme_abc_thumb_upload($variables) {

    $element = $variables['element'];

    if (isset($element['#file']->uri)) {
        $output = '<div id="edit-logo-ajax-wrapper"><div class="form-item form-type-managed-file form-item-logo"><span class="file">';
        $output .= '<img height="50px" src="' . file_create_url($element['#file']->uri) . '" />';
        $output .= '</span><input type="submit" id="edit-' . $element['#name'] . '-remove-button" name="' . $element['#name'] . '_remove_button" value="Remove" class="form-submit ajax-processed">';
        $output .= '<input type="hidden" name="' . $element['#name'] . '[fid]" value="' . $element['#file']->fid . '">';

        return $output;
    }
}

/**
 * Implments hook_uc_add_to_cart
 */
function tcss_cart_uc_add_to_cart_data($form_values) {
  //dpm($form_values);
}

/**
 * Implements hook_uc_product_alter
 */
function tcss_cart_uc_product_alter(&$node){
  // Update product quantity when user add product to his cart
  $node->default_qty = $node->pkg_qty;
}

function tcss_cart_uc_order($op, $order, $arg2) {
  //dpm($op);
  //dpm($order);
  //dpm($arg2);
}

/**
 * Implements hook_uc_cart_checkout_start
 * Need to be changed, should be saved in hook_uc_order
 */
function tcss_cart_uc_cart_checkout_start($order) {

  // Save Product image to database
  if (isset($_SESSION['customer_artwork_fpid'])) {
    foreach ($order->products as $id => $product) {
      $order_id = $order->order_id;
      $product_image = new stdClass();
      $product_image->type = 'product_image';
      node_object_prepare($product_image);
      $image = (array) file_load($_SESSION['customer_artwork_fpid'][$product->nid]);
      $product_image->language = LANGUAGE_NONE;
      $product_image->field_order_id['und'][0]['value'] = $order_id;
      $product_image->field_order_product_id['und'][0]['target_id'] = $product->nid;
      $product_image->field_order_prodcut_image['und'][0] = $image;
      node_save($product_image);
    }
    unset($_SESSION['customer_artwork_fpid']);
  }
 }
